/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ConditionRisk = IDL.Record({
  'conditionName' : IDL.Text,
  'riskLevel' : IDL.Text,
});
export const Assessment = IDL.Record({
  'ageBucket' : IDL.Text,
  'conditionRisks' : IDL.Vec(ConditionRisk),
  'conditions' : IDL.Vec(IDL.Text),
  'symptoms' : IDL.Vec(IDL.Text),
  'overallRiskLevel' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAggregatedStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'riskLevelBreakdown' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int)),
          'topConditions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int)),
          'totalAssessments' : IDL.Int,
          'topSymptoms' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int)),
        }),
      ],
      ['query'],
    ),
  'submitAssessment' : IDL.Func([Assessment], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ConditionRisk = IDL.Record({
    'conditionName' : IDL.Text,
    'riskLevel' : IDL.Text,
  });
  const Assessment = IDL.Record({
    'ageBucket' : IDL.Text,
    'conditionRisks' : IDL.Vec(ConditionRisk),
    'conditions' : IDL.Vec(IDL.Text),
    'symptoms' : IDL.Vec(IDL.Text),
    'overallRiskLevel' : IDL.Text,
  });
  
  return IDL.Service({
    'getAggregatedStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'riskLevelBreakdown' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int)),
            'topConditions' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int)),
            'totalAssessments' : IDL.Int,
            'topSymptoms' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int)),
          }),
        ],
        ['query'],
      ),
    'submitAssessment' : IDL.Func([Assessment], [], []),
  });
};

export const init = ({ IDL }) => { return []; };